[project]
name = "mongerswaps"
description = "Demonstrates mongerswap's submarine swaps between Stacks and Bitcoin"
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.mongerswaps]
path = "contracts/mongerswaps.clar"
clarity_version = 4
epoch = "latest"

[repl.analysis]
passes = []

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
